"""
Refresh self-hosted webfonts in frontend/public/fonts/ from Google Fonts.

Run once after the broken stubs are replaced:
    python3 scripts/refresh-fonts.py

The previous stubs in public/fonts/ were 1.6 KB HTML 404 pages saved with a
.woff2 extension, which made every weight except `noto-serif-500` fail to load.
This rebuilds the directory + frontend/src/styles/fonts.css from authoritative
gstatic URLs.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "frontend" / "public" / "fonts"
CSS_PATH = ROOT / "frontend" / "src" / "styles" / "fonts.css"

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
)

FAMILIES = [
    {
        "name": "Be Vietnam Pro",
        "slug": "be-vietnam-pro",
        "url": "https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700&display=swap",
    },
    {
        "name": "Noto Serif",
        "slug": "noto-serif",
        # ital,wght: 0,500;0,600;0,700 = upright; 1,500;1,600 = italic.
        "url": "https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,500;0,600;0,700;1,500;1,600&display=swap",
    },
]

# We only ship these subsets — the app is Vietnamese-only and shipping
# cyrillic/greek/math/etc adds ~MB of woff2 we never render.
ALLOWED_SUBSETS = {"latin", "latin-ext", "vietnamese"}

FACE_RE = re.compile(
    r"/\*\s*(?P<subset>[a-z0-9-]+)\s*\*/\s*"
    r"@font-face\s*\{(?P<body>[^}]+)\}",
    re.IGNORECASE,
)


def http_get(url: str) -> str:
    return subprocess.check_output(
        ["curl", "-fsSL", "-A", UA, url], timeout=30
    ).decode("utf-8")


def http_download(url: str, dest: Path) -> int:
    subprocess.check_call(
        ["curl", "-fsSL", "-A", UA, "-o", str(dest), url], timeout=30
    )
    return dest.stat().st_size


def parse_field(body: str, field: str) -> str:
    m = re.search(rf"{field}\s*:\s*([^;]+);", body, re.IGNORECASE)
    if not m:
        raise ValueError(f"missing {field} in {body!r}")
    return m.group(1).strip()


def parse_src_url(body: str) -> str:
    m = re.search(r"src\s*:\s*url\(([^)]+)\)", body, re.IGNORECASE)
    if not m:
        raise ValueError(f"missing src url in {body!r}")
    return m.group(1).strip().strip("'\"")


def main() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)

    out_blocks: list[str] = []

    for fam in FAMILIES:
        print(f"-- {fam['name']}")
        css = http_get(fam["url"])
        for match in FACE_RE.finditer(css):
            subset = match.group("subset").lower()
            if subset not in ALLOWED_SUBSETS:
                continue
            body = match.group("body")
            weight = parse_field(body, "font-weight")
            style = parse_field(body, "font-style")
            unicode_range = parse_field(body, "unicode-range")
            src_url = parse_src_url(body)

            local_name = (
                f"{fam['slug']}-{weight}-{style}-{subset}.woff2"
            )
            dest = FONTS_DIR / local_name
            size = http_download(src_url, dest)
            print(f"   {local_name:54s} {size:>7d} bytes  ({subset})")

            out_blocks.append(
                "@font-face {\n"
                f"  font-family: \"{fam['name']}\";\n"
                f"  font-style: {style};\n"
                f"  font-weight: {weight};\n"
                f"  font-display: swap;\n"
                f"  src: url(\"/fonts/{local_name}\") format(\"woff2\");\n"
                f"  unicode-range: {unicode_range};\n"
                "}"
            )

    header = (
        "/* Self-hosted fonts for offline Capacitor support.\n"
        "   Regenerated by scripts/refresh-fonts.py from Google Fonts.\n"
        "   Each weight ships per-subset (latin / latin-ext / vietnamese)\n"
        "   so Vietnamese diacritics resolve from the Vietnamese subset\n"
        "   instead of being faux-rendered from Latin glyphs. */\n\n"
    )
    CSS_PATH.write_text(header + "\n\n".join(out_blocks) + "\n")
    print(f"-- wrote {CSS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
